Repository horang-edu/FE, pull requests merged in 2023-09, with the labels that each got.

#2 init : 초기셋팅
  package.json
  postcss.config.js
  tailwind.config.js
  yarn.lock
Labels: setting

#4 #3 init : 공통 레이아웃
  src/App.js
  src/assets/img/dashboard.png
  src/assets/img/home.png
  src/assets/img/line.png
  src/assets/img/logo.png
  src/assets/img/practice.png
  src/assets/img/study.png
  src/assets/svg/dashboard.svg
  src/assets/svg/home.svg
  src/assets/svg/practice.svg
  src/assets/svg/study.svg
  src/components/common/layout/Layout.jsx
  src/components/common/sidebar/Sidebar.jsx
  src/index.css
  src/pages/Dashboard.jsx
  src/pages/Home.jsx
  src/pages/Practice.jsx
  src/pages/Study.jsx
  src/shared/Router.jsx
  src/style/reset.css
  src/style/style.css
  tailwind.config.js
Labels: setting

#8 #7 design:출석체크 및 미션 컴포넌트
  package.json
  src/assets/svg/Stamp.svg
  src/assets/svg/StampO.png
  src/components/Mission/Calendar.jsx
  src/components/Mission/Mission.jsx
  src/components/Mission/Modal.jsx
  src/index.js
  src/shared/Router.js
  src/style/styles.css
  tailwind.config.js
  yarn.lock
Labels: frontend, UI

#9 #3 init : 레이아웃 수정
  src/App.js
  src/index.js
  src/pages/Home.jsx
  src/shared/Router.js
  src/style/reset.css
  src/style/style.css
  src/style/styles.css
Labels: setting

#13 #12 design : 사이드바 아이콘 색상 변경 추가
  src/assets/svg/dashboardHover.svg
  src/assets/svg/homeHover.svg
  src/assets/svg/practiceHover.svg
  src/assets/svg/studyHover.svg
  src/components/common/sidebar/Sidebar.jsx
Labels: frontend, UI

#15 #3 init : 사이드바 아이콘 크기 수정
  src/components/common/sidebar/Sidebar.jsx
Labels: setting

#14 #5 feat : 오늘의 과제 및 찜목록 기능 연결 및 검사
  src/App.js
  src/assets/delete.svg
  src/assets/false.svg
  src/assets/true.svg
  src/components/Todaystask.js
  src/components/Wishlist.js
  src/style/styles.css
Labels: frontend, feature

#16 #11 design : 출석체크, 미션 모달 CSS
  src/components/Mission/Modal.jsx
  src/pages/Min.jsx
  src/shared/Router.jsx
  src/style/styles.css
  tailwind.config.js
Labels: frontend, UI

#17 fix : 병합 에러 수정
  src/style/styles.css
Labels: fix

#21 #5 fix : api 수정 및 css 보완
  src/App.js
  src/assets/img/dashboradimg.png
  src/components/Progress.js
  src/components/Todaystask.js
  src/components/Wishlist.js
  src/pages/Dashboard.jsx
  src/style/styles.css
Labels: bug, frontend, feature, fix

#23 #11 feat : Modal 출석체크 및 미션 컴포넌트 api 연결
  .gitignore
  package.json
  postcss.config.js
  src/App.js
  src/assets/svg/calendarBackground.svg
  src/assets/svg/star.svg
  src/assets/svg/studyBackground.svg
  src/components/Mission/AttendanceTab.jsx
  src/components/Mission/CalendarMission.jsx
  src/components/Mission/Modal.jsx
  src/components/Mission/ReactCalender.jsx
  src/index.js
  src/pages/Min.jsx
  src/style/styles.css
  tailwind.config.js
  yarn.lock
Labels: frontend, feature, UI

#27 #26 init : 서버 연결 셋팅
  src/App.js
  src/apis/instance.js
  src/apis/ranking.js
  src/components/Progress.js
  src/index.js
Labels: setting

#29 design:홈화면 UI
  src/components/Mission/Mission.jsx
  src/pages/Home.jsx
Labels: frontend, UI

#31 #24 design:메인 CSS
  src/components/Mission/Mission.jsx
  src/components/Mission/Modal.jsx
  src/components/announcement/Announcement.jsx
  src/components/announcement/QA.jsx
  src/components/tab/Tab.jsx
  src/pages/Home.jsx
  src/style/styles.css
Labels: frontend, UI

#33 #32 design : 메인 레이아웃 및 CSS
  src/assets/svg/alarm.svg
  src/assets/svg/logo.svg
  src/components/Mission/CalendarMission.jsx
  src/components/Update.jsx
  src/components/announcement/Announcement.jsx
  src/components/announcement/QA.jsx
  src/pages/Home.jsx
Labels: frontend, UI

#36 #32 design : 레이아웃
  src/components/Mission/CalendarMission.jsx
  src/components/ranking/CampusRanking.jsx
  src/components/ranking/SchoolRanking.jsx
  src/components/ranking/UserRanking.jsx
  src/components/tab/Tab.jsx
  src/pages/Home.jsx
  src/style/styles.css
Labels: frontend, UI, fix

#43 #41 design : 나의학습방 QnA 디자인
  src/components/qna/Answer.jsx
  src/components/qna/Question.jsx
  src/components/tab/Tab.jsx
  src/pages/Dashboard.jsx
  src/pages/Home.jsx
Labels: UI

#48 fix : api 수정 및 인스턴스 연결
  src/apis/mystudyroom.js
  src/components/Progress.js
  src/components/Todaystask.js
  src/components/Wishlist.js
Labels: frontend, fix

#50 fix : api 수정
  src/apis/attendance.js
Labels: bug

#53 #32 fix : favicon 추가
  src/assets/img/favicon.png
Labels: UI
